# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_post_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
    ]
